### ISSUE TITLE
fullscreen only in mobile screen

### ISSUE THREAD

**Issue by webmobiles** [TeamWertarbyte/material-ui-fullscreen-dialog#10]
is this component fullscreen when screen width is small ?
i look for a component that be full scren only when the screen is small, I mean responsive.

**Comment by leMaik** [comment]
This component _always_ displays in fullscreen mode. If you want to use a normal `Dialog` on larger screens, you can use something like [react-responsive](https://github.com/contra/react-responsive):


```
import Dialog from 'material-ui/Dialog'
import FullscreenDialog from 'material-ui-fullscreen-dialog'
import MediaQuery from 'react-responsive'

<MediaQuery query='(min-device-width: 1225px)'>
  <Dialog>
    Your dialog content here...
  </Dialog>
</MediaQuery>
<MediaQuery query='(max-width: 1224px)'>
  <FullscreenDialog>
    Your dialog content here...
  </FullscreenDialog>
</MediaQuery>
```

**Comment by webmobiles** [comment]
thanks !
