### ISSUE TITLE
Invalid prop `appBarZDepth` of value `0` supplied to `FullscreenDialog`, expected one of [1,2,3,4,5]

### ISSUE THREAD

**Issue by Rick83600** [TeamWertarbyte/material-ui-fullscreen-dialog#12]
Heyyy :)

Why the property appBarZDepth cannot be set to 0 without this warning ?

Thanks

**Comment by leMaik** [comment]
Because I [didn't allow it to be zero](https://github.com/TeamWertarbyte/material-ui-fullscreen-dialog/blob/master/src/FullscreenDialog.js#L78). PR welcome!
