### ISSUE TITLE
Update react-transition-group

### ISSUE THREAD

**Issue by Minivera** [TeamWertarbyte/material-ui-fullscreen-dialog#15]
The version of `react-transition-group` required as a peer dependency is outdated and still uses the v1 API. Since most users are likely to install the newest version (For example, if they have `react-router` installed before this package and want to animate the transition), it would be great to update the version and API.

While I understand this could be fixed by using material UI 1.0, we are many who will not have updated in the near future and this issue prevents any full screen dialog from working.

I have create this PR #16 that fixes the issue and implement the new API.

**Comment by leMaik** [comment]
Thank you, @Minivera. I'll release a new major version soon (since this is a breaking change).
