### ISSUE TITLE
Hide body scrollbar when FullScreenDialog is open

### ISSUE THREAD

**Issue by hugochinchilla** [TeamWertarbyte/material-ui-fullscreen-dialog#3]
If the page containgin the `FullScreenDialog` is swowing a scrollbar the `FullScreenDialog` should set `{overflow: 'hidden'}` to body until the dialog is closed

**Comment by leMaik** [comment]
@hugochinchilla I'll release v1.3.0 soon, after I update material-ui and react.
Totally forgot about this issue. :see_no_evil:
